#!/bin/bash

source hooks/_conf

function docker_manifest_annotate_tag() {

    local DOCKER_TAG="$1"
    DOCKER_PLATFORM_NAME="$2"

    DOCKER_PLATFORM="$(echo "${DOCKER_PLATFORMS}" | jq -cr "select(.platform == \"${DOCKER_PLATFORM_NAME}\")")"

    DOCKER_PLATFORM_ARCH="$(echo "${DOCKER_PLATFORM}" | jq -r '.architecture')"

    DOCKER_MANIFEST_ANNOTATE_ARGS="${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG} --os linux --arch ${DOCKER_PLATFORM_ARCH}"

    DOCKER_PLATFORM_VARIANT="$(echo "${DOCKER_PLATFORM}" | jq -r '.variant')"
    if [ "${DOCKER_PLATFORM_VARIANT}" != "null" ]; then
        DOCKER_MANIFEST_ANNOTATE_ARGS="${DOCKER_MANIFEST_ANNOTATE_ARGS} --variant ${DOCKER_PLATFORM_VARIANT}"
    fi

    echo "$(date '+%H:%M:%S') Annotating ${DOCKER_REPO}:${DOCKER_TAG} manifest with ${DOCKER_MANIFEST_ANNOTATE_ARGS}..."
    docker manifest annotate "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_MANIFEST_ANNOTATE_ARGS}
}

function docker_manifest_tag() {

    local DOCKER_TAG="${1:1}"
    echo "$(date '+%H:%M:%S') Creating manifest ${DOCKER_REPO}:${DOCKER_TAG}..."

    DOCKER_PLATFORM_REPOS=""
    for DOCKER_PLATFORM_NAME in ${DOCKER_PLATFORM_NAMES}; do
        echo "$(date '+%H:%M:%S') Pulling ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}..."
        docker pull "${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}" > /dev/null 2>&1 || true
        if [ "$(docker image ls -q "${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}")" == "" ]; then
            echo "$(date '+%H:%M:%S') Image ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG} not found"
            exit 0
        fi
        DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS} ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}"
    done

    DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS:1}"

    echo "$(date '+%H:%M:%S') Creating manifest ${DOCKER_REPO}:${DOCKER_TAG} for ${DOCKER_PLATFORM_REPOS}..."
    docker manifest create "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_PLATFORM_REPOS}

    for DOCKER_PLATFORM_NAME in ${DOCKER_PLATFORM_NAMES}; do
        docker_manifest_annotate_tag "${DOCKER_TAG}" "${DOCKER_PLATFORM_NAME}"
    done

    echo "$(date '+%H:%M:%S') Pushing manifest ${DOCKER_REPO}:${DOCKER_TAG}..."
    docker manifest push "${DOCKER_REPO}:${DOCKER_TAG}"
}

docker_manifest_tag "${DOCKER_TAG_REV}"
docker_manifest_tag "${DOCKER_TAG}"
