#!/bin/bash

source hooks/_conf

function docker_push() {
    DOCKER_PLATFORM_NAME="$1"
    echo "$(date '+%H:%M:%S') Pushing ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}${DOCKER_TAG_REV}..."
    docker push "${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}${DOCKER_TAG_REV}"

    echo "$(date '+%H:%M:%S') Pushing ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}${DOCKER_TAG}..."
    docker push "${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}${DOCKER_TAG}" 
}

if [ "${DOCKER_PLATFORM_NAME}" != "" ]; then
    docker_push "${DOCKER_PLATFORM_NAME}"
else
    for DOCKER_PLATFORM_NAME in ${DOCKER_PLATFORM_NAMES}; do
        docker_push "${DOCKER_PLATFORM_NAME}"
    done
fi
