#!/bin/bash

source hooks/_conf

for DOCKER_PLATFORM in ${DOCKER_PLATFORMS}; do
    DOCKER_PLATFORM_NAME="$(echo "${DOCKER_PLATFORM}" | jq -r '.platform')"
    docker push ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}
done
